{
    "name": "Bahmni Module Install",
    "version": "6.0",
    "depends": [
                "base",
                "auth_crypt",
                "product",
                "account",
                "account_voucher",
                "purchase",
                "account_accountant",
                "stock",
                "sale",
                "sale_stock",
                "purchase",
                "product_expiry",
                "bahmni_web_extensions",
                "bahmni_pharmacy_product",
                "bahmni_stock_batch_sale_price",
                "bahmni_sale_discount",
                "bahmni_customer_payment",
                "bahmni_internal_stock_move",
                ],
    "author": "ThoughtWorks Technologies Pvt. Ltd.",
    "category": "Setup",
    "summary": "Install Module",
    "description": """
    """,
    'data': [],
    'demo': [],
    'auto_install': True,
    'application': True,
    'installable': True,
#    'certificate': 'certificate',
}
