{
    "name": "Bahmni web framework extensions",
    "version": "1.0",
    "depends": ["base","web"],
    "author": "ThoughtWorks Technologies Pvt. Ltd.",
    "category": "",
	"summary": "Extend web framework like base templates, javascript etc",
    "description": """
    """,
    'data': [],
    'demo': [],
    'qweb': ['static/src/xml/*.xml'],
    'css': ['static/src/css/extension.css'],
    'js': [
        'static/src/js/init.js',
        'static/src/js/fixingErrorInCancelEdition.js',
        'static/src/js/addingAccessKeyToOne2ManyList.js',
        'static/src/js/accesskeyHighlight.js',
        'static/src/js/addSerialNumberToListView.js',
        'static/src/js/addContextOnExport.js',
    ],
    'auto_install': False,
    'application': True,
    'installable': True,
}
